version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-1.8.0"
    PATH: "$JAVA_HOME/bin:$PATH"

phases:
  install:
    commands:
      - echo "Entered the install phase..."
      - echo "Updating packages..."
      - yum update -y
      - echo "Installing Maven..."
      - yum install -y maven
    finally:
      - echo "This always runs even if the update or install command fails"

  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      # - echo "You can add login or setup commands here"
    finally:
      - echo "This always runs even if the pre_build command fails"

  build:
    commands:
      - echo "Entered the build phase..."
      - echo "Build started on $(date)"
      - cd my-webapp
      - echo "Running Maven install..."
      - mvn clean install
    finally:
      - echo "This always runs even if the build command fails"

  post_build:
    commands:
      - echo "Entered the post_build phase..."
      - echo "Build completed on $(date)"
      # - echo "You can add artifact upload or deploy steps here"
