version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-1.8.0"
    PATH: "$JAVA_HOME/bin:$PATH"

phases:
  install:
    commands:
      - echo "Entered the install phase..."
      - echo "Skipping system updates — not needed for this image"
    finally:
      - echo "Install phase completed"

  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      - echo "Preparing for build..."
    finally:
      - echo "Pre-build phase completed"

  build:
    commands:
      - echo "Entered the build phase..."
      - echo "Build started on $(date)"
      - cd my-webapp
      - echo "Running Maven build..."
      - mvn clean install
    finally:
      - echo "Build phase completed"

  post_build:
    commands:
      - echo "Entered the post_build phase..."
      - echo "Build completed successfully on $(date)"
